
ARCHS?=i386 x86_64
ARCHOPTS=$(addprefix -arch ,$(ARCHS))

FRAMEWORKS=Cocoa Foundation

FLAGS+=-D__MACOSX_CORE__ -D__MAUI_CHUGIN__ $(ARCHOPTS)
LDFLAGS+=-shared -lstdc++ $(addprefix -framework ,$(FRAMEWORKS)) \
-ObjC $(ARCHOPTS) \
-Wl,-undefined,dynamic_lookup

LD=clang++
CXX=clang++
OBJCXX=clang++
